spring.application.name=scms

#MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/scms_db
spring.datasource.username=root
spring.datasource..password=MYSQLrishikarashmi@5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update

#show SQL quries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server port
server.port=8080